In [1]:
import pandas as pd
import geopandas as gpd

In [42]:
def read_data(path, sheet_name):
    data = pd.read_excel(path, sheet_name=sheet_name)
    
    data = data[data['QC Status'] == 'Pass']
    
    data = data[
        (data["Act.Code"].str.startswith("LP", na=False)) &
        (~data["Act.Name"].str.contains("Pitting for Blanking", case=False, na=False))
    ]
    
    data['WO_creation_date'] = pd.to_datetime(data['WO_creation_date'])
    data = data.sort_values(by="WO_creation_date", ascending=True)
    
    return data

In [43]:
data = read_data(r"C:\Users\LENOVO\Downloads\Akwaaba work order tracker (1).xlsx",sheet_name="work_order_tracker")

In [44]:
data

,MF_ID,WO_ID,WO_creation_date,reserve,subcomp_id,area_ha,partial_area_ha,activity_code,activity_full,team_id,...,Landuse,Area,Act.Code,Act.Name,Compt. Name,Work Invoiced,Mandays Budgeted,Mandays Used,Ac QC Work Failed,QC Status
13,138,AEA-A19c_LP003_Jan 1,2025-01-01,Anhwiaso east,AEA-A19c,13.588,5.0250,LP003,Manual site clearing / Bush clearing,Anhwiaso South Team 4,...,A19c,19.56,LP003,Manual site clearing / Bush clearing,AEA-A19c,5.0250,NaN,NaN,NaN,Pass
14,139,AEA-A19c_LP003_Jan 1,2025-01-01,Anhwiaso east,AEA-A19c,13.588,4.4670,LP003,Manual site clearing / Bush clearing,Anhwiaso South Team 14,...,A19c,18.20,LP003,Manual site clearing / Bush clearing,AEA-A19c,4.4670,NaN,NaN,NaN,Pass
15,140,AEA-A19c_LP003_Jan 1,2025-01-01,Anhwiaso east,AEA-A19c,13.588,0.6150,LP003,Manual site clearing / Bush clearing,Anhwiaso South Team 5,...,A19c,1.07,LP003,Manual site clearing / Bush clearing,AEA-A19c,0.6150,NaN,NaN,NaN,Pass
16,142,ASO-B6a_LP005_Jan 1,2025-01-01,Anhwiaso South,ASO-B6a,28.420,5.0100,LP005,Line Cutting & Clearing for Enrichment Plant 1...,Anhwiaso South Team 1,...,B6a,5.10,LP005,Line Cutting & Clearing for Enrichment Plant 1...,ASO-B6a,5.0100,NaN,NaN,NaN,Pass
17,152,UWA-B59g_LP005_Jan 1,2025-01-01,Upper Wassaw,UWA-B59g,19.112,8.2390,LP005,Line Cutting & Clearing for Enrichment Plant 1...,Anhwiaso South Team 2,...,B59g,37.55,LP005,Line Cutting & Clearing for Enrichment Plant 1...,UWA-B59g,8.2390,NaN,NaN,NaN,Pass
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4661,4348,UWA-B59i_LP003_Oct 1,2025-10-01,Upper Wassaw,UWA-B59i,13.581,0.4464,LP003,Manual site clearing / Bush clearing,Anhwiaso South Team 13,...,B59i,13.73,LP003,Manual site clearing / Bush clearing,UWA-B59i,0.4464,6.25,7.0,NaN,Pass
4662,4349,UWA-B59j_LP003_Oct 1,2025-10-01,Upper Wassaw,UWA-B59j,16.645,0.4646,LP003,Manual site clearing / Bush clearing,Anhwiaso South Team 6,...,B59j,16.65,LP003,Manual site clearing / Bush clearing,UWA-B59j,0.4646,6.50,6.0,NaN,Pass
4663,4350,ASO-B17a1_LP004_Oct 1,2025-10-01,Anhwiaso South,ASO-B17a1,19.816,0.2894,LP004,Land prep-Slashing,Upper Wassaw Team 8,...,B17a1,19.70,LP004,Land prep-Slashing,ASO-B17a1,0.2894,0.87,3.0,NaN,Pass
4539,3504,UWA-B51a_LP009_Oct 1,2025-10-01,Upper Wassaw,UWA-B51a,32.103,1.5705,LP009,Marking and Pitting 3 x 3,Upper Wassaw Team 6,...,B51a,32.08,LP009,Marking and Pitting 3 x 3,UWA-B51a,1.5705,17.28,14.0,NaN,Pass
5073,4895,ASO-B10a1_LP013_Oct 1,2025-10-01,Anhwiaso South,ASO-B10a1,16.662,8.9610,LP013,Blanking 4 x 4,Anhwiaso South Team 3,...,B10a1,16.65,LP013,Blanking 4 x 4,ASO-B10a1,8.9610,34.05,52.0,NaN,Pass

In [45]:


grouped = (
    data
    .groupby("subcomp_id")
    .agg(
        # subcomp_id=("subcomp_id", "max"),
        land_prep_start_date=("WO_creation_date", "min"),
        land_prep_activity=("Act.Name", "max"),
      
    )
    .reset_index()
)

In [47]:
grouped.sort_values(by="land_prep_start_date", ascending=True).to_csv('land_prep_start_date_2025.csv')

In [27]:
grouped.sort_values(by="land_prep_start_date", ascending=True)

    subcomp_id land_prep_start_date                    land_prep_activity
52    AEA-A19c           2025-01-01             Top Slashing for Spraying
284   UWA-B59g           2025-01-01  Manual site clearing / Bush clearing
176    ASO-B6a           2025-01-01             Marking and Pitting 5 x 3
283   UWA-B59f           2025-01-01             Top Slashing for Spraying
169    ASO-B5a           2025-01-01             Marking and Pitting 3 x 3
..         ...                  ...                                   ...
246   UWA-B50b           2025-10-01             Marking and Pitting 3 x 3
238   UWA-B49g           2025-10-01  Manual site clearing / Bush clearing
157  ASO-B13c3           2025-10-01             Marking and Pitting 5 x 3
22    AEA-A12i           2025-10-01             Marking and Pitting 5 x 3
249   UWA-B50j           2025-10-01                   Line Clearing 3 x 3

[299 rows x 3 columns]

In [7]:
def read_data(path,):
    test_data = gpd.read_file(path)
    return test_data

In [11]:
def retrieve_project(data,project_name):
    project_data = data[data['project']==project_name]
    dropped_project_column = project_data.loc[:, project_data.columns != 'project']
    return dropped_project_column

In [8]:
test_data = read_data(r"C:\Users\LENOVO\Downloads\test_subcomps_akw_buf.gpkg")

In [14]:
buffalo = retrieve_project(test_data,'akwaaba')

In [15]:
buffalo

,compartment_id,subcompartment_id,area_ha,treatment_type,planting_status,year_planted,planting_type,lp_start_date,plant_start_date,geometry
2,None,test1,NaN,None,None,NaT,None,NaT,NaT,"POLYGON ((-2.30592 6.43199, -2.30607 6.43198, ..."
3,None,test2,NaN,None,None,NaT,None,NaT,NaT,"POLYGON ((-2.30589 6.43176, -2.3058 6.43178, -..."

In [3]:
test_data

,project,compartment_id,subcompartment_id,area_ha,treatment_type,planting_status,year_planted,planting_type,lp_start_date,plant_start_date,geometry
0,buffalo,None,test1,NaN,None,None,NaT,None,NaT,NaT,"POLYGON ((-12.21129 8.33372, -12.21185 8.33385..."
1,buffalo,None,test2,NaN,None,None,NaT,None,NaT,NaT,"POLYGON ((-12.21177 8.33423, -12.21126 8.33413..."
2,akwaaba,None,test1,NaN,None,None,NaT,None,NaT,NaT,"POLYGON ((-2.30592 6.43199, -2.30607 6.43198, ..."
3,akwaaba,None,test2,NaN,None,None,NaT,None,NaT,NaT,"POLYGON ((-2.30589 6.43176, -2.3058 6.43178, -..."